export { ReactComponent as FacebookOutLine } from "./facebook.svg";
export { ReactComponent as GithubOutLine } from "./github.svg";
export { ReactComponent as LinkedInOutline } from "./linkedin.svg"
export { ReactComponent as CaretDownOutLine } from "./caret-down.svg"
export { ReactComponent as XMarkOutline } from "./xmark.svg";
export { ReactComponent as CircleInfoOutline } from "./circle-info.svg";
export { ReactComponent as ArrowUpOutline } from "./arrow-up.svg";
export { ReactComponent as ArrowLeftOutline } from "./arrow-left.svg";
export { ReactComponent as DoubleLeftOutline } from "./double-left.svg";
export { ReactComponent as DoubleRightOutline } from "./double-right.svg";
export { ReactComponent as PhoneOutline } from "./phone.svg";
export { ReactComponent as MailOutline } from "./mail.svg";
export { ReactComponent as HomeOutline } from "./home.svg";
export { ReactComponent as SettingOutline } from "./setting.svg";
export { ReactComponent as ZaloOutline } from "./zalo.svg";
export { ReactComponent as GlobalOutline } from "./global.svg";
export { ReactComponent as SunOutline } from "./sun.svg";
export { ReactComponent as MoonOutline } from "./moon.svg";
export { ReactComponent as PaperPlane } from "./paper-plane.svg";