export { ReactComponent as FacebookOutLine } from "./facebook.svg";
export { ReactComponent as GithubOutLine } from "./github.svg";
export { ReactComponent as LinkedInOutline } from "./linkedin.svg"
export { ReactComponent as CaretDownOutLine } from "./caret-down.svg"
export { ReactComponent as XMarkOutline } from "./xmark.svg";
export { ReactComponent as CircleInfoOutline } from "./circle-info.svg";
export { ReactComponent as ArrowUpOutline } from "./arrow-up.svg";
export { ReactComponent as ArrowLeftOutline } from "./arrow-left.svg";
export { ReactComponent as ArrowRightOutline } from "./arrow-right.svg";